(function(){
'use strict';

var D=window.INVENTORY_DEMO_DATA;
if(!D){console.error('库存优化样例数据未加载');return;}

var FLOW={
  monthly:{code:'KCYH-001',title:'月度成品库存策略制定',desc:'每月25日形成次月成品库存策略，完成评审、确认、审批、发布并进入周度分解。',nodes:[
    ['10','形成下月需求与策略计算范围','库存计划员','CRM月度计划、明确订单、库存与排程快照','下月成品范围与计算边界','确认成品、周期与有效数据版本；非成品不进入计算。','数据异常记录隔离后提示复核','INV-M-010'],
    ['20','生成月度库存策略','SCOS系统','需求日拆分、SS、周期、S、库容','SS/s/S与月度总补充量草案','按日复核的(R,s,S)生成策略；先独立计算，再校验兼容库容。','超容量时保留原建议并给出最大可执行量','INV-M-020'],
    ['30','评审月度策略','库存计划员','月度策略草案、风险与容量校验','评审意见','核对服务、库存、节奏、容量和数据口径。','可退回节点20重算','INV-M-030'],
    ['40','确认月度策略','库存负责人','评审通过草案','已确认策略','确认参数、总量和建议节奏，不直接创建生产任务。','不通过则保留有效版本','INV-M-040'],
    ['50','审批月度策略','供应链总监','已确认策略与评审记录','审批结论','审批版本、输入快照和策略差异。','驳回后回到评审','INV-M-050'],
    ['60','发布策略与月度总补充量','SCOS系统','审批通过策略','正式策略版本','固化策略版本、输入快照、参数版本、审批人与发布时间。','发布失败不替换有效版本','INV-M-060'],
    ['70','进入周度计划分解','库存计划员','已发布月度策略','周度计算任务','把月度策略作为未来4周补充计划输入。','缺少发布版本时禁止进入','INV-M-070']
  ]},
  weekly:{code:'KCYH-002',title:'周度生产补充计划制定',desc:'每周五计算未来4周日度补充量，按周六至周五汇总，锁定第1周后发布。',nodes:[
    ['10','汇集周度计划输入','SCOS系统','策略、需求、库存、在途、排程、质量、罐容','周度输入快照','只使用正常数据；冲突数据按确认版本处理。','输入不完整时禁止发布','INV-W-010'],
    ['20','生成未来4周日度补充量','SCOS系统','输入快照与(R,s,S)参数','28天日度补充建议','明确订单优先；其余月计划均摊；到达s时补至S。','第1周已确认量不自动改写','INV-W-020'],
    ['30','按周汇总','SCOS系统','28天日度建议','4个周六至周五汇总','汇总需求、已有入库、新增补充和期望可用日期。','跨周日量以可用入库日归周','INV-W-030'],
    ['40','评审周度计划','库存计划员','周汇总与日明细','评审意见','核对需求、库存风险与共享罐容量。','容量冲突返回节点20调整','INV-W-040'],
    ['50','库存侧确认','库存负责人','评审通过计划','库存侧确认记录','确认第1周候选锁定量及未来3周滚动建议。','未确认不能提交生产承接','INV-W-050'],
    ['60','生产侧承接','生产计划员','库存侧确认计划','承接状态','对各周给出已承接、部分承接或不承接。','未承接量保留风险提示','INV-W-060'],
    ['70','确认纳入生产排程','生产计划员','承接结论','排程确认记录','确认纳入排程和预计可用入库时间。','未纳入不能锁定','INV-W-070'],
    ['80','锁定第1周','库存负责人','排程确认记录','锁定周明细','锁定未来7天；只允许预警，不自动修改数量。','锁定失败保留待锁定状态','INV-W-080'],
    ['90','发布周度计划','SCOS系统','第1周已锁定计划','周度计划版本','向生产排程输出周总量、日明细和期望可用日期。','接口失败记录重试任务','INV-W-090']
  ]},
  daily:{code:'KCYH-003',title:'日度库存监控、滚动校验与滚动锁定',desc:'每日滚动未来4周；锁定期只预警，第2至第4周可形成调整建议并反馈排程。',nodes:[
    ['10','汇集日度监控数据','SCOS系统','日出货、库存、在途、排程、质检、罐状态','日度监控快照','汇集需求、4周建议与当前排程。','过期/冲突数据隔离并提示','INV-D-010'],
    ['20','滚动测算未来4周','SCOS系统','日度快照与有效策略','日度库存投影','递推期初、需求、可用入库与期末库存。','待检库存放行前不计可用','INV-D-020'],
    ['30','判断是否存在风险','SCOS系统','库存投影、SS、s、S、容量','风险日清单','识别缺货、低于SS、容量冲突和执行缺口。','无风险则持续监控','INV-D-030'],
    ['40','判断是否处于锁定期','SCOS系统','风险日与滚动锁定窗口','锁定/非锁定分流','按T+7判断是否允许调整。','边界日以已锁定标识为准','INV-D-040'],
    ['50','生成锁定期预警','SCOS系统','锁定期风险','预警事件','说明缺口、原因、影响期和建议协同动作。','不改变锁定补充量','INV-D-050'],
    ['60','记录预警并保持第1周锁定','库存负责人','预警事件','保持锁定确认','记录处置责任和保持锁定标识。','必要时线下升级协调','INV-D-060'],
    ['70','非锁定期预警与调整建议','SCOS系统','第2至4周风险','调整前后差异草案','按(R,s,S)生成未锁定期调整建议并校验容量。','不可消除风险必须保留说明','INV-D-070'],
    ['80','库存侧复核并提交','库存计划员','调整建议草案','库存侧复核记录','核对后提交生产计划员。','可退回重算','INV-D-080'],
    ['90','生产侧判断是否调整','生产计划员','复核建议与产能排程','采纳/不采纳结论','记录是否调整及原因。','不采纳时风险继续跟踪','INV-D-090'],
    ['100','反馈排程并滚动锁定T+7','生产计划员','采纳结论','排程调整任务与预计可用日','反馈排程；每日向后滚动锁定1天。','接口失败保留待反馈状态','INV-D-100']
  ]},
  abnormal:{code:'KCYH-004',title:'库存策略异常调整',desc:'重大需求、产能、库容或补充周期变化触发月中重算，形成独立版本。',nodes:[
    ['10','识别重大变化事件','库存计划员','需求、订单、停机、罐状态、补充周期变化','事件记录','区分重大变化与普通库存波动。','普通波动转日度监控，不重算策略','INV-A-010'],
    ['20','识别影响范围','SCOS系统','重大事件','受影响成品与期间','定位受影响产品、时间、服务和容量。','范围不完整时请求人工补充','INV-A-020'],
    ['30','判断是否需要重算','库存负责人','影响评估','重算结论','达到重大变化条件才进入策略调整。','无需重算则记录并返回监控','INV-A-030'],
    ['40','生成调整后策略','SCOS系统','原策略、事件参数、最新快照','调整策略草案','仅重算受影响产品和期间，保留前后差异。','容量不足时保留未消除风险','INV-A-040'],
    ['50','评审调整策略','库存计划员','调整草案与差异','评审意见','核对SS/s/S、补充量、服务和罐容变化。','可退回节点40','INV-A-050'],
    ['60','审批调整策略','供应链总监','评审通过草案','审批结论','审批调整原因、影响和残余风险。','驳回不改变当前有效策略','INV-A-060'],
    ['70','发布新版本','SCOS系统','审批通过调整策略','新策略版本','保留原版本、输入、参数、结果和审批轨迹。','发布失败保持原版本有效','INV-A-070']
  ]},
  health:{code:'KCYH-005',title:'库存健康度评价与策略改进',desc:'按月评价周转、满足率、缺货、容量与库龄，形成改进建议但不自动改写正式策略。',nodes:[
    ['10','汇集策略与执行数据','SCOS系统','策略版本、库存、订单、排程、质量、容量事件','健康评价数据集','关联计划、执行和风险结果。','缺失数据标注评价置信度','INV-H-010'],
    ['20','生成健康度评价','SCOS系统','评价数据集','指标与等级','计算平均库存、周转天数、订单满足率、缺货、超容量与库龄。','异常值进入复核清单','INV-H-020'],
    ['30','复核策略有效性','库存计划员','健康度指标与差异','有效性结论','区分参数、需求、执行、质量和容量原因。','无法归因则标记待观察','INV-H-030'],
    ['40','判断是否需要改进','库存负责人','有效性结论','改进判断','决定改进或保持观察。','无需改进仍发布结论','INV-H-040'],
    ['50','形成改进建议','库存计划员','原因与指标','参数/周期/执行建议','形成SS、S、补充周期或复核周期建议。','建议不自动生效','INV-H-050'],
    ['60','判断是否纳入策略调整','库存负责人','改进建议','纳入路径','选择下月策略、异常调整或观察。','异常调整需走KCYH-004','INV-H-060'],
    ['70','发布健康度报告','SCOS系统','评价结论与纳入路径','报告与跟踪任务','发布报告并向驾驶舱输出健康度。','发布失败保留草稿','INV-H-070']
  ]}
};

var STATE={tab:0,product:'FG-F55',monthlyStep:2,weeklyStep:3,abnormalStep:0,healthStep:2,
  monthlyStatus:'有效版本 V1.0',weeklyStatus:'计算草案',dailyAction:'待处置',scenario:'demand',scenarioRun:false,abnormalPublished:false,healthPublished:false,
  params:{},audit:D.audit.slice(),projection:{},lastSnapshot:D.meta.snapshotTime};
D.products.forEach(function(p){STATE.params[p.code]={safetyStock:p.safetyStock,targetStock:p.targetStock,leadDays:p.leadDays,batchSize:p.batchSize,batchEnabled:p.batchEnabled};});

function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function fmt(n,d){return Number(n||0).toLocaleString('zh-CN',{minimumFractionDigits:d||0,maximumFractionDigits:d||0});}
function dateAdd(ds,n){var d=new Date(ds+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);}
function shortDate(ds){return ds.slice(5).replace('-','/');}
function getProduct(code){return D.products.find(function(p){return p.code===(code||STATE.product);});}
function param(p){return STATE.params[p.code];}
function available(p){return p.stock.qualified-p.stock.allocated-p.stock.frozen-p.stock.qualityAbnormal;}
function monthDates(){var a=[];for(var i=1;i<=30;i++)a.push('2026-10-'+String(i).padStart(2,'0'));return a;}
function demandMap(p,mult){var dates=monthDates(),explicit=p.explicitOrders||{},sum=Object.values(explicit).reduce(function(a,b){return a+b;},0),open=dates.filter(function(d){return explicit[d]==null;}),remain=Math.max(0,p.monthlyPlan*(mult||1)-sum),avg=open.length?remain/open.length:0,m={};dates.forEach(function(d){m[d]=explicit[d]!=null?explicit[d]*(mult||1):avg;});return m;}
function capacityFor(p){return D.tanks.filter(function(t){return t.available&&t.compatibleProducts.indexOf(p.code)>=0&&!t.qcTank;}).reduce(function(a,t){return a+t.workCapacity;},0);}
function groupCapacity(group){var ts=D.tanks.filter(function(t){return t.group===group&&!t.qcTank;}),cap=ts.filter(function(t){return t.available;}).reduce(function(a,t){return a+t.workCapacity;},0),qty=ts.filter(function(t){return t.available;}).reduce(function(a,t){return a+t.currentQty;},0);return {capacity:cap,current:qty,headroom:Math.max(0,cap-qty)};}
function monthlyCalc(p,override,mult){var q=override||param(p),dm=demandMap(p,mult),receipts=(p.scheduledReceipts||[]).reduce(function(a,r){return a+r.qty;},0)+p.effectiveTransit,total=Object.values(dm).reduce(function(a,b){return a+b;},0),raw=Math.max(0,total+q.safetyStock-available(p)-receipts),replen=q.batchEnabled?Math.ceil(raw/q.batchSize)*q.batchSize:Math.ceil(raw),grp=groupCapacity(p.tankGroup),maxExec=Math.min(replen,Math.max(0,grp.headroom+total)),excess=Math.max(0,replen-maxExec);return {demand:total,receipts:receipts,replen:replen,maxExec:maxExec,excess:excess,capacity:capacityFor(p),group:grp};}
function project(p,opts){
  opts=opts||{};var q=Object.assign({},param(p),opts.params||{}),mult=opts.demandMult||1,lead=q.leadDays+(opts.leadExtra||0),dm=demandMap(p,mult),fixed={},plans={},dates=[],rows=[],open=available(p),transitDate=dateAdd(D.meta.horizonStart,2),grp=groupCapacity(p.tankGroup),capacity=capacityFor(p);
  (p.scheduledReceipts||[]).forEach(function(r){fixed[r.date]=(fixed[r.date]||0)+r.qty;});fixed[transitDate]=(fixed[transitDate]||0)+p.effectiveTransit;
  for(var i=0;i<D.meta.horizonDays;i++)dates.push(dateAdd(D.meta.horizonStart,i));
  dates.forEach(function(day,idx){
    var demand=dm[day]||0,incoming=(fixed[day]||0)+(plans[day]||0),opening=open,closing=opening+incoming-demand,leadDemand=0;
    for(var k=0;k<lead;k++)leadDemand+=dm[dateAdd(day,k)]||0;
    var reorder=leadDemand+q.safetyStock,pipeline=0;
    Object.keys(fixed).forEach(function(x){if(x>day&&x<=dateAdd(day,lead))pipeline+=fixed[x];});Object.keys(plans).forEach(function(x){if(x>day&&x<=dateAdd(day,lead))pipeline+=plans[x];});
    var ip=closing+pipeline,raw=0,suggested=0,capExcess=0,due=dateAdd(day,lead);
    if(idx>=D.meta.lockDays&&ip<=reorder){raw=Math.max(0,q.targetStock-ip);suggested=q.batchEnabled?Math.ceil(raw/q.batchSize)*q.batchSize:Math.ceil(raw);var maxExec=Math.max(0,grp.headroom+leadDemand);capExcess=Math.max(0,suggested-maxExec);suggested=Math.min(suggested,maxExec);plans[due]=(plans[due]||0)+suggested;}
    var risk=closing<0?'缺货':closing<q.safetyStock?'低于SS':closing>capacity?'容量冲突':capExcess>0?'补充受容量约束':'正常';
    rows.push({date:day,index:idx,opening:opening,demand:demand,incoming:incoming,closing:closing,reorder:reorder,target:q.targetStock,ip:ip,raw:raw,suggested:suggested,due:due,capExcess:capExcess,risk:risk,locked:idx<D.meta.lockDays});open=closing;
  });
  return rows;
}
function projections(){var out={};D.products.forEach(function(p){out[p.code]=project(p);});return out;}
function allRisks(){var arr=[];Object.keys(STATE.projection).forEach(function(code){STATE.projection[code].forEach(function(r){if(r.risk!=='正常')arr.push(Object.assign({product:getProduct(code)},r));});});return arr.sort(function(a,b){return a.date.localeCompare(b.date);});}
function weeklyRows(p){var rows=STATE.projection[p.code]||project(p),out=[];for(var w=0;w<4;w++){var sub=rows.slice(w*7,w*7+7),need=sub.reduce(function(a,r){return a+r.demand;},0),existing=sub.reduce(function(a,r){return a+r.incoming;},0),added=sub.reduce(function(a,r){return a+r.suggested;},0),risks=sub.filter(function(r){return r.risk!=='正常';}),due=sub.filter(function(r){return r.suggested>0;}).map(function(r){return r.due;});out.push({week:w+1,start:sub[0].date,end:sub[sub.length-1].date,demand:need,existing:existing,added:added,risk:risks.length?risks[0].risk:'正常',due:due[0]||'—',locked:w===0,status:w===0?'已承接':w===1?'部分承接':w===2?'待确认':'不承接'});}return out;}
function riskTag(r){var c=r==='正常'?'green':r==='缺货'||r==='容量冲突'?'red':'yellow';return '<span class="tag tag-'+c+'">'+esc(r)+'</span>';}
function statusTag(s){var c=/成功|正常|有效|已发布|已承接|已锁定|绿/.test(s)?'green':/待|部分|黄|草案|观察|过期/.test(s)?'yellow':/失败|不承接|冲突|红|缺/.test(s)?'red':'blue';return '<span class="tag tag-'+c+'">'+esc(s)+'</span>';}
function metric(label,value,note,color){return '<div class="kpi-card inv-metric '+(color||'blue')+'"><div class="kpi-label">'+label+'</div><div class="kpi-value">'+value+'</div><div class="inv-metric-note">'+note+'</div></div>';}
function summary(label,value,state){return '<div class="inv-summary-item '+(state||'')+'"><div class="inv-summary-label">'+label+'</div><div class="inv-summary-value">'+value+'</div></div>';}
function flowHTML(type,step){var f=FLOW[type];return '<div class="card mb-16"><div class="inv-process-head"><div><div class="inv-process-title">'+f.code+' · '+f.title+'</div><div class="inv-process-desc">'+f.desc+' 点击节点查看角色、输入输出、处理与异常规则。</div></div>'+statusTag(type==='monthly'?STATE.monthlyStatus:type==='weekly'?STATE.weeklyStatus:type==='health'?(STATE.healthPublished?'报告已发布':'评价中'):type==='abnormal'?(STATE.abnormalPublished?'新版本已发布':STATE.scenarioRun?'调整草案':'待识别'):'每日滚动')+'</div><div class="inv-flow">'+f.nodes.map(function(n,i){var cls=i<step?'done':i===step?'active':'',lock=(type==='weekly'&&i===7)||(type==='daily'&&i===5)?' locked':'';return '<button class="inv-flow-node '+cls+lock+'" onclick="invV1OpenNode(\''+type+'\','+i+')"><span class="inv-flow-id"><span>'+f.code+'-'+n[0]+'</span><span>'+(i<step?'✓':i===step?'●':'○')+'</span></span><span class="inv-flow-title">'+n[1]+'</span><span class="inv-flow-role">'+n[2]+'</span></button>'+(i<f.nodes.length-1?'<span class="inv-flow-arrow">›</span>':'');}).join('')+'</div></div>';}
function productOptions(){return D.products.map(function(p){return '<option value="'+p.code+'" '+(p.code===STATE.product?'selected':'')+'>'+p.name+' · '+p.code+'</option>';}).join('');}
function productSelect(extra){return '<label class="inv-field wide">成品<select class="inv-select" onchange="invV1SelectProduct(this.value,'+(extra||STATE.tab)+')">'+productOptions()+'</select></label>';}
function header(){return '<div class="page-header"><div><div class="page-title">成品库存优化</div><div class="page-subtitle">Finished Goods Inventory Optimization · 动态 (R, s, S) · 月/周/日/事件闭环</div><div class="inv-topline"><span class="inv-version">'+esc(D.meta.strategyId)+' / '+esc(D.meta.strategyVersion)+'</span><span class="text-xs text-muted">快照 '+esc(STATE.lastSnapshot)+' · 参数 '+esc(D.meta.parameterVersion)+' · 仅成品</span></div></div><div class="inv-actions"><button class="btn btn-sm" onclick="invV1Refresh()">刷新快照</button><button class="btn btn-sm" onclick="invV1Entities()">数据实体与接口</button><button class="btn btn-sm btn-green" onclick="invV1Export()">导出样例数据</button></div></div>';}
function tabs(){var names=['运行总览','月度策略','周度补充','日度监控','异常调整','健康度'];return '<div class="tab-bar inv-tabs">'+names.map(function(n,i){return '<button class="tab-btn inv-tab-btn '+(i===STATE.tab?'active':'')+'" onclick="invV1Switch('+i+')"><span class="inv-tab-index">'+i+'</span>'+n+'</button>';}).join('')+'</div>';}

function overviewHTML(){var risks=allRisks(),critical=risks.filter(function(r){return r.risk==='缺货'||r.risk==='容量冲突';}),healthy=D.health.filter(function(h){return h.level==='绿';}).length;return '<div class="inv-grid-5 mb-16">'+metric('有效策略',D.meta.strategyVersion,'2026年10月 · 已发布','blue')+metric('未来4周风险',String(risks.length),critical.length+' 条红色风险','yellow')+metric('锁定窗口',D.meta.lockDays+'天',D.meta.horizonStart+' 起','purple')+metric('数据质量','4/6正常','过期1 · 冲突1','cyan')+metric('健康成品',healthy+'/'+D.products.length,'绿/黄/红分级','green')+'</div><div class="grid grid-2 gap-16 mb-16"><div class="card"><div class="card-title"><span class="dot" style="background:var(--blue)"></span>五流程运行状态</div><div class="inv-life">'+[['monthly','月度策略','V1.0 已发布'],['weekly','周度补充','第1周已锁定'],['daily','日度监控',risks.length+'条风险'],['abnormal','异常调整','待事件触发'],['health','健康度','2绿1黄1红']].map(function(x,i){return '<div class="inv-life-card" onclick="invV1Switch('+(i+1)+')"><div class="inv-life-name">'+FLOW[x[0]].code+'<br>'+x[1]+'</div><div class="inv-life-meta">'+x[2]+'<br>点击进入流程</div>'+statusTag(i<3?'运行中':i===3?'待触发':'需改进')+'</div>';}).join('')+'</div></div><div class="card"><div class="card-title"><span class="dot" style="background:var(--cyan)"></span>共享库容与罐状态</div><div class="inv-tank-grid">'+['TG-SYRUP','TG-POWDER-LIQUID'].map(function(g){var x=groupCapacity(g),pct=Math.min(100,x.current/x.capacity*100);return '<div class="inv-tank"><div class="inv-tank-head"><span>'+g+'</span>'+statusTag(pct>85?'高占用':'可用')+'</div><div class="inv-tank-meta"><span>'+fmt(x.current)+' / '+fmt(x.capacity)+'吨</span><span>余量 '+fmt(x.headroom)+'吨</span></div><div class="inv-tank-track"><div class="inv-tank-fill" style="width:'+pct.toFixed(1)+'%"></div></div></div>';}).join('')+'</div><div class="text-xs text-muted mt-12">TK-MD-02 检修停用；QC罐不得拆分至多个成品罐，待检数量放行前不计入可用库存。</div></div></div><div class="grid grid-32 gap-16 mb-16"><div class="card"><div class="card-title"><span class="dot" style="background:var(--yellow)"></span>未来4周风险清单 <span class="tag tag-yellow" style="margin-left:auto">点击钻取</span></div>'+riskTable(risks.slice(0,8))+'</div><div class="card"><div class="card-title"><span class="dot" style="background:var(--purple)"></span>数据源与质量</div><div class="inv-source-list">'+D.dataQualityRecords.map(function(x){return '<div class="inv-source-row"><span class="inv-source-id">'+x.source+'</span><span>'+x.object+'</span><span>'+x.timestamp.slice(5)+'</span>'+statusTag(x.status)+'</div>';}).join('')+'</div></div></div><div class="card"><div class="card-title"><span class="dot" style="background:var(--green)"></span>最近审计轨迹</div>'+auditHTML()+'</div>';}
function riskTable(rows){if(!rows.length)return '<div class="inv-empty">当前筛选范围没有库存风险</div>';return '<div class="overflow-auto"><table class="data-table"><thead><tr><th>日期</th><th>成品</th><th>期末库存</th><th>SS</th><th>风险</th><th>窗口</th><th>建议处置</th></tr></thead><tbody>'+rows.map(function(r){var locked=r.locked;return '<tr class="inv-risk-row" tabindex="0" role="button" onclick="invV1OpenRisk(\''+r.product.code+'\',\''+r.date+'\')" onkeydown="if(event.key===\'Enter\'||event.key===\' \'){event.preventDefault();invV1OpenRisk(\''+r.product.code+'\',\''+r.date+'\')}"><td class="text-mono">'+r.date+'</td><td>'+r.product.name+'</td><td class="text-mono '+(r.closing<0?'text-red':'')+'">'+fmt(r.closing,0)+'吨</td><td class="text-mono">'+fmt(param(r.product).safetyStock)+'吨</td><td>'+riskTag(r.risk)+'</td><td><span class="inv-lock-band"><span class="inv-dot '+(locked?'lock':'roll')+'"></span>'+(locked?'T+7锁定':'滚动区')+'</span></td><td>'+(locked?'记录预警，保持锁定量':'形成调整建议并提交生产端')+'</td></tr>';}).join('')+'</tbody></table></div>';}
function auditHTML(){return '<div class="inv-audit">'+STATE.audit.slice().reverse().slice(0,8).map(function(a){return '<div class="inv-audit-row"><span class="text-mono">'+a.time+'</span><span>'+a.user+'</span><span>'+a.action+'</span><span class="text-mono">'+a.object+'</span>'+statusTag(a.result)+'</div>';}).join('')+'</div>';}

function monthlyHTML(){var p=getProduct(),q=param(p),c=monthlyCalc(p),dm=demandMap(p),avg=Object.values(dm).reduce(function(a,b){return a+b;},0)/30;return flowHTML('monthly',STATE.monthlyStep)+'<div class="inv-toolbar mb-16">'+productSelect(1)+'<label class="inv-field">安全库存 SS（吨）<input id="invSS" class="inv-input" type="number" min="0" value="'+q.safetyStock+'"></label><label class="inv-field">目标库存 S（吨）<input id="invTarget" class="inv-input" type="number" min="1" value="'+q.targetStock+'"></label><label class="inv-field">补充周期（天）<input id="invLead" class="inv-input" type="number" min="1" max="15" value="'+q.leadDays+'"></label><label class="inv-field">最小批量（吨）<input id="invBatch" class="inv-input" type="number" min="1" value="'+q.batchSize+'"></label><label class="inv-check"><input id="invBatchOn" type="checkbox" '+(q.batchEnabled?'checked':'')+'>启用批量取整</label><button class="btn btn-primary btn-sm" onclick="invV1RecalcMonthly()">生成参数草案</button></div><div class="inv-summary mb-16">'+summary('月度计划需求',fmt(c.demand)+'吨')+summary('当前可用库存',fmt(available(p))+'吨')+summary('月度总补充建议',fmt(c.replen)+'吨',c.excess?'warning':'success')+summary('共享罐组最大可执行',fmt(c.maxExec)+'吨',c.excess?'danger':'')+'</div><div class="grid grid-2 gap-16 mb-16"><div class="card"><div class="card-title"><span class="dot" style="background:var(--cyan)"></span>需求日拆分 · 明确订单优先</div><div id="invMonthlyDemandChart" class="inv-chart"></div><div class="text-xs text-muted">明确订单 '+Object.keys(p.explicitOrders).length+' 天；其余计划按无明确订单日期均摊，参考日均 '+fmt(avg,1)+'吨。</div></div><div class="card"><div class="card-title"><span class="dot" style="background:var(--purple)"></span>策略参数与容量校验</div><div class="inv-summary">'+summary('正式 SS / 参考天数',fmt(q.safetyStock)+'吨 / '+p.safetyDaysReference+'天')+summary('按日 s','需求至最早可用日 + SS')+summary('目标 S',fmt(q.targetStock)+'吨')+summary('兼容工作容量',fmt(c.capacity)+'吨')+'</div><div class="inv-status-panel '+(c.excess?'danger':'success')+' mt-12">'+(c.excess?'<b>容量约束：</b>原始建议超出可执行能力 '+fmt(c.excess)+'吨。页面保留原始建议与最大可执行量，由计划员调整未锁定部分。':'<b>校验通过：</b>当前月度建议未超过兼容工作容量。')+'<br>SS为人工维护正式值；“安全库存天数×计划日均”仅作参考，不自动替换。</div></div></div>'+monthlyTable()+'<div class="card"><div class="card-title"><span class="dot" style="background:var(--green)"></span>月度策略审批与发布</div>'+workflowBar(['计算','评审','确认','审批','发布','周度分解'],Math.min(5,STATE.monthlyStep-1))+'<div class="inv-actions mt-12"><button class="btn btn-primary btn-sm" onclick="invV1AdvanceMonthly()">'+(STATE.monthlyStep>=6?'重新进入周度分解':'执行下一节点')+'</button><button class="btn btn-sm" onclick="invV1ResetMonthly()">退回参数草案</button><span class="text-xs text-muted">草案不改变有效策略；完成发布后才生成新版本。</span></div></div>';}
function monthlyTable(){return '<div class="card mb-16"><div class="card-title"><span class="dot" style="background:var(--blue)"></span>全成品月度策略草案</div><div class="overflow-auto"><table class="data-table"><thead><tr><th>成品</th><th>月计划</th><th>可用库存</th><th>SS</th><th>S</th><th>补充周期</th><th>总补充建议</th><th>罐组</th><th>校验</th></tr></thead><tbody>'+D.products.map(function(p){var c=monthlyCalc(p),q=param(p);return '<tr><td>'+p.name+'<br><span class="text-xs text-muted">'+p.code+'</span></td><td class="text-mono">'+fmt(c.demand)+'</td><td class="text-mono">'+fmt(available(p))+'</td><td class="text-mono">'+fmt(q.safetyStock)+'</td><td class="text-mono">'+fmt(q.targetStock)+'</td><td class="text-mono">'+q.leadDays+'天</td><td class="text-mono text-cyan">'+fmt(c.replen)+'</td><td class="text-mono">'+p.tankGroup+'</td><td>'+riskTag(c.excess?'容量约束':'正常')+'</td></tr>';}).join('')+'</tbody></table></div></div>';}
function workflowBar(names,active){return '<div class="workflow">'+names.map(function(n,i){return '<div class="wf-step '+(i<active?'done':i===active?'active':'pending')+'"><div class="wf-dot">'+(i<active?'✓':i+1)+'</div><div class="wf-name">'+n+'</div></div>'+(i<names.length-1?'<div class="wf-line '+(i<active?'done':'')+'"></div>':'');}).join('')+'</div>';}

function weeklyHTML(){var p=getProduct(),rows=weeklyRows(p);return flowHTML('weekly',STATE.weeklyStep)+'<div class="inv-toolbar mb-16">'+productSelect(2)+'<div class="inv-status-panel" style="flex:1"><b>计算日：</b>'+D.meta.weeklyCalcDate+'（周五） · <b>周界：</b>周六至下周五 · <b>锁定：</b>第1周/T+7<br>只有生产确认纳入排程后，才可锁定第1周并发布。</div><button class="btn btn-primary btn-sm" onclick="invV1AdvanceWeekly()">执行下一节点</button></div><div class="grid grid-2 gap-16 mb-16"><div class="card"><div class="card-title"><span class="dot" style="background:var(--blue)"></span>未来4周日度补充与库存</div><div id="invWeeklyChart" class="inv-chart"></div></div><div class="card"><div class="card-title"><span class="dot" style="background:var(--yellow)"></span>生产承接与锁定</div>'+workflowBar(['输入','日度计算','周汇总','评审','确认','承接','排程','锁定','发布'],Math.min(8,STATE.weeklyStep))+'<div class="inv-status-panel '+(STATE.weeklyStep>=8?'success':'warning')+' mt-12">'+(STATE.weeklyStep>=8?'第1周已锁定；锁定期内只预警，不自动改量。':'当前为草案/承接阶段；第1周尚未完成正式发布。')+'</div></div></div><div class="card"><div class="card-title"><span class="dot" style="background:var(--cyan)"></span>周度汇总与生产承接</div><div class="overflow-auto"><table class="data-table"><thead><tr><th>周次</th><th>期间</th><th>计划流出</th><th>已有可用入库</th><th>新增补充</th><th>期望可用日</th><th>风险</th><th>生产承接</th><th>锁定</th></tr></thead><tbody>'+rows.map(function(r){return '<tr><td>W'+r.week+'</td><td class="text-mono">'+shortDate(r.start)+'–'+shortDate(r.end)+'</td><td class="text-mono">'+fmt(r.demand)+'</td><td class="text-mono">'+fmt(r.existing)+'</td><td class="text-mono text-cyan">'+fmt(r.added)+'</td><td class="text-mono">'+r.due+'</td><td>'+riskTag(r.risk)+'</td><td><select class="inv-select" '+(r.locked?'disabled':'')+' onchange="invV1AcceptWeek('+r.week+',this.value)"><option '+(r.status==='已承接'?'selected':'')+'>已承接</option><option '+(r.status==='部分承接'?'selected':'')+'>部分承接</option><option '+(r.status==='不承接'?'selected':'')+'>不承接</option><option '+(r.status==='待确认'?'selected':'')+'>待确认</option></select></td><td>'+(r.locked?statusTag('已锁定'):statusTag('滚动建议'))+'</td></tr>';}).join('')+'</tbody></table></div></div>';}

function dailyHTML(){var p=getProduct(),rows=STATE.projection[p.code],risks=rows.filter(function(r){return r.risk!=='正常';}).map(function(r){return Object.assign({product:p},r);});return flowHTML('daily',Math.min(9,risks.length?4:2))+'<div class="inv-toolbar mb-16">'+productSelect(3)+'<span class="inv-lock-band"><span class="inv-dot lock"></span>T+7锁定期</span><span class="inv-lock-band" style="color:var(--blue)"><span class="inv-dot roll"></span>第2–4周滚动区</span><button class="btn btn-sm" onclick="invV1RollLock()">模拟次日滚动锁定</button></div><div class="inv-grid-5 mb-16">'+metric('期初可用',fmt(available(p))+'吨','不含待检 '+fmt(p.stock.pendingInspection)+'吨','blue')+metric('安全库存 SS',fmt(param(p).safetyStock)+'吨','正式维护值','cyan')+metric('目标库存 S',fmt(param(p).targetStock)+'吨','触发补至目标','purple')+metric('未来4周风险',String(risks.length),'点击下表风险钻取','yellow')+metric('T+7锁定',D.meta.lockDays+'天','只预警不改量','green')+'</div><div class="card mb-16"><div class="card-title"><span class="dot" style="background:var(--cyan)"></span>未来4周日度库存投影 <span class="tag tag-blue" style="margin-left:auto">R=每日复核</span></div><div id="invDailyChart" class="inv-chart tall"></div><div class="text-xs text-muted">公式：期末可用 = 期初可用 + 当日计划可用入库 + 新增补充到货 − 当日需求。待检库存放行前不计入。</div></div><div class="grid grid-32 gap-16"><div class="card"><div class="card-title"><span class="dot" style="background:var(--yellow)"></span>风险与锁定期分流</div>'+riskTable(risks)+'</div><div class="card"><div class="card-title"><span class="dot" style="background:var(--green)"></span>处置状态</div><div class="inv-status-panel '+(STATE.dailyAction==='待处置'?'warning':'success')+'"><b>'+STATE.dailyAction+'</b><br>锁定期风险：记录预警并保持锁定量。<br>非锁定期风险：生成差异草案 → 库存复核 → 生产判断 → 反馈排程。</div><div class="inv-actions mt-12"><button class="btn btn-yellow btn-sm" onclick="invV1HandleDaily(true)">记录锁定期预警</button><button class="btn btn-primary btn-sm" onclick="invV1HandleDaily(false)">提交非锁定期调整</button></div></div></div>';}

var EVENTS={demand:{title:'需求计划上调',desc:'受影响成品月计划上调',value:20,unit:'%',major:true},order:{title:'大客户订单增加',desc:'F55新增指定日期订单',value:680,unit:'吨',major:true},line:{title:'产线长期停机',desc:'补充周期额外延长',value:4,unit:'天',major:true},tank:{title:'共享储罐停用',desc:'糖浆罐组减少可用容量',value:1200,unit:'吨',major:true},lead:{title:'补充周期延长',desc:'最早可用日期后移',value:3,unit:'天',major:true}};
function scenarioResult(){var e=EVENTS[STATE.scenario],p=getProduct(),base=monthlyCalc(p),newP=Object.assign({},param(p)),mult=1,extra=0;if(STATE.scenario==='demand')mult=1+e.value/100;if(STATE.scenario==='order')mult=1+e.value/p.monthlyPlan;if(STATE.scenario==='line'||STATE.scenario==='lead')extra=e.value;if(STATE.scenario==='tank')newP.targetStock=Math.min(newP.targetStock,Math.max(newP.safetyStock+1,newP.targetStock-e.value*.2));var adj=monthlyCalc(p,newP,mult),proj=project(p,{params:newP,demandMult:mult,leadExtra:extra}),risk=proj.filter(function(r){return r.risk!=='正常';}).length;return {event:e,base:base,adj:adj,newP:newP,mult:mult,extra:extra,risk:risk};}
function abnormalHTML(){var e=EVENTS[STATE.scenario],r=scenarioResult(),p=getProduct();return flowHTML('abnormal',STATE.abnormalStep)+'<div class="card mb-16"><div class="card-title"><span class="dot" style="background:var(--purple)"></span>重大变化事件</div><div class="inv-event-grid">'+Object.keys(EVENTS).map(function(k){var x=EVENTS[k];return '<button class="inv-event '+(STATE.scenario===k?'active':'')+'" onclick="invV1Event(\''+k+'\')"><div class="inv-event-title">'+x.title+'</div><div class="inv-event-desc">'+x.desc+' · '+x.value+x.unit+'</div></button>';}).join('')+'</div><div class="inv-toolbar mt-12">'+productSelect(4)+'<label class="inv-field">事件幅度<input id="invEventValue" class="inv-input" type="number" value="'+e.value+'"></label><span class="text-xs text-muted">'+e.unit+' · 普通库存波动应回到日度监控，不触发策略重算。</span><button class="btn btn-primary btn-sm" onclick="invV1RunScenario()">识别影响并生成草案</button></div></div>'+(STATE.scenarioRun?'<div class="grid grid-2 gap-16 mb-16"><div class="card"><div class="card-title"><span class="dot" style="background:var(--blue)"></span>调整前后比较</div><div class="inv-compare"><div class="inv-compare-card">'+summary('有效版本',D.meta.strategyVersion)+summary('SS / S',param(p).safetyStock+' / '+param(p).targetStock+'吨')+summary('月度补充',fmt(r.base.replen)+'吨')+summary('风险','基线投影')+'</div><div class="inv-compare-arrow">→</div><div class="inv-compare-card">'+summary('调整草案','V1.1-DRAFT')+summary('SS / S',r.newP.safetyStock+' / '+r.newP.targetStock+'吨')+summary('月度补充',fmt(r.adj.replen)+'吨',r.adj.excess?'danger':'warning')+summary('风险日',r.risk+'天',r.risk?'danger':'success')+'</div></div></div><div class="card"><div class="card-title"><span class="dot" style="background:var(--yellow)"></span>影响识别与残余风险</div><div class="inv-status-panel '+(r.risk?'danger':'success')+'"><b>'+r.event.title+'</b>影响 '+p.name+'；需求倍率 '+r.mult.toFixed(2)+'，补充周期额外 '+r.extra+' 天。<br>'+(r.adj.excess?'共享库容导致 '+fmt(r.adj.excess)+'吨暂不可执行；保留未消除风险。':'容量校验未发现额外不可执行量。')+'</div><div class="inv-actions mt-12"><button class="btn btn-primary btn-sm" onclick="invV1AdvanceAbnormal()">评审 / 审批 / 发布</button><button class="btn btn-sm" onclick="invV1ResetScenario()">放弃草案</button></div></div></div><div class="card"><div class="card-title"><span class="dot" style="background:var(--cyan)"></span>调整情景日度投影</div><div id="invScenarioChart" class="inv-chart"></div></div>':'<div class="inv-empty">选择重大变化事件后运行影响识别。情景不会改写已发布基线。</div>');}

function healthHTML(){var avg=D.health.reduce(function(a,h){return a+h.orderFillRate;},0)/D.health.length,red=D.health.filter(function(h){return h.level==='红';}).length;return flowHTML('health',STATE.healthStep)+'<div class="inv-grid-5 mb-16">'+metric('订单满足率',(avg*100).toFixed(1)+'%','四成品加权演示值','green')+metric('缺货次数',fmt(D.health.reduce(function(a,h){return a+h.stockoutCount;},0)),'评价期累计','yellow')+metric('超容量次数',fmt(D.health.reduce(function(a,h){return a+h.overcapacityCount;},0)),'共享罐组事件','purple')+metric('滞销/呆滞/临期',fmt(D.health.reduce(function(a,h){return a+h.slowQty+h.obsoleteQty+h.expiringQty;},0))+'吨','库龄风险合计','cyan')+metric('红色成品',String(red),'需进入改进闭环','red')+'</div><div class="grid grid-32 gap-16 mb-16"><div class="card"><div class="card-title"><span class="dot" style="background:var(--green)"></span>成品库存健康度明细</div><div class="overflow-auto"><table class="data-table"><thead><tr><th>成品</th><th>平均库存</th><th>周转天数</th><th>满足率</th><th>缺货</th><th>超容量</th><th>库龄风险</th><th>等级</th><th>有效性</th></tr></thead><tbody>'+D.health.map(function(h){var p=getProduct(h.productCode);return '<tr><td>'+p.name+'</td><td class="text-mono">'+fmt(h.averageStock)+'</td><td class="text-mono">'+h.inventoryDays+'</td><td class="text-mono">'+(h.orderFillRate*100).toFixed(1)+'%</td><td class="text-mono">'+h.stockoutCount+'</td><td class="text-mono">'+h.overcapacityCount+'</td><td class="text-mono">'+fmt(h.slowQty+h.obsoleteQty+h.expiringQty)+'吨</td><td>'+statusTag(h.level)+'</td><td>'+statusTag(h.effectiveness)+'</td></tr>';}).join('')+'</tbody></table></div></div><div class="card"><div class="card-title"><span class="dot" style="background:var(--purple)"></span>综合健康度</div><div id="invHealthChart" class="inv-chart compact"></div></div></div><div class="card mb-16"><div class="card-title"><span class="dot" style="background:var(--yellow)"></span>原因与改进建议</div><div class="overflow-auto"><table class="data-table"><thead><tr><th>成品</th><th>原因归类</th><th>改进建议</th><th>纳入路径</th></tr></thead><tbody>'+D.health.map(function(h){return '<tr><td>'+getProduct(h.productCode).name+'</td><td>'+h.cause+'</td><td>'+h.suggestion+'</td><td><select class="inv-select"><option>'+(h.level==='红'?'异常调整':h.level==='黄'?'下月策略':'保持观察')+'</option><option>下月策略</option><option>异常调整</option><option>保持观察</option></select></td></tr>';}).join('')+'</tbody></table></div></div><div class="card"><div class="card-title"><span class="dot" style="background:var(--blue)"></span>评价发布</div>'+workflowBar(['汇集数据','生成评价','复核','判断改进','形成建议','纳入判断','发布报告'],STATE.healthStep)+'<div class="inv-actions mt-12"><button class="btn btn-primary btn-sm" onclick="invV1AdvanceHealth()">'+(STATE.healthPublished?'查看已发布报告':'执行下一节点')+'</button><span class="text-xs text-muted">建议不会自动改写正式策略；负责人选择下月策略、异常调整或观察。</span></div></div>';}

function render(){var el=document.getElementById('page-inventory');if(!el)return;STATE.projection=projections();var bodies=[overviewHTML,monthlyHTML,weeklyHTML,dailyHTML,abnormalHTML,healthHTML];el.innerHTML='<div class="inv-shell">'+header()+tabs()+'<div class="inv-v1-body">'+bodies[STATE.tab]()+'</div></div>';setTimeout(initCharts,0);}
function initCharts(){var p=getProduct(),q=param(p),dm=demandMap(p),dates=Object.keys(dm);if(STATE.tab===1){initChart('invMonthlyDemandChart',mOpt({tooltip:{trigger:'axis'},legend:{data:['计划需求','明确订单'],top:0,right:0},xAxis:{type:'category',data:dates.map(shortDate)},yAxis:{type:'value',name:'吨'},series:[{name:'计划需求',type:'bar',data:dates.map(function(d){return +dm[d].toFixed(1);}),itemStyle:{color:'rgba(59,130,246,.55)'}},{name:'明确订单',type:'scatter',data:dates.map(function(d){return p.explicitOrders[d]||null;}),symbolSize:8,itemStyle:{color:'#f59e0b'}}]}));}
  if(STATE.tab===2){var rows=STATE.projection[p.code];initChart('invWeeklyChart',mOpt({tooltip:{trigger:'axis'},legend:{data:['期末可用','SS','新增补充'],top:0,right:0},xAxis:{type:'category',data:rows.map(function(r){return shortDate(r.date);})},yAxis:[{type:'value',name:'库存/吨'},{type:'value',name:'补充/吨'}],series:[{name:'期末可用',type:'line',smooth:true,data:rows.map(function(r){return +r.closing.toFixed(1);}),itemStyle:{color:'#06b6d4'},markArea:{silent:true,data:[[{xAxis:0,itemStyle:{color:'rgba(245,158,11,.07)'}},{xAxis:6}]]}},{name:'SS',type:'line',symbol:'none',data:rows.map(function(){return q.safetyStock;}),lineStyle:{type:'dashed',color:'#ef4444'}},{name:'新增补充',type:'bar',yAxisIndex:1,data:rows.map(function(r){return r.suggested;}),itemStyle:{color:'rgba(59,130,246,.55)'}}]}));}
  if(STATE.tab===3){var dr=STATE.projection[p.code];var ch=initChart('invDailyChart',mOpt({tooltip:{trigger:'axis'},legend:{data:['期末可用','SS','按日s','目标S','当日入库'],top:0,right:0},xAxis:{type:'category',data:dr.map(function(r){return shortDate(r.date);})},yAxis:{type:'value',name:'吨'},series:[{name:'期末可用',type:'line',smooth:true,data:dr.map(function(r){return +r.closing.toFixed(1);}),itemStyle:{color:'#06b6d4'},areaStyle:{color:'rgba(6,182,212,.07)'},markArea:{silent:true,data:[[{name:'T+7锁定',xAxis:0,itemStyle:{color:'rgba(245,158,11,.08)'}},{xAxis:6}]]}},{name:'SS',type:'line',symbol:'none',data:dr.map(function(){return q.safetyStock;}),lineStyle:{type:'dashed',color:'#ef4444'}},{name:'按日s',type:'line',symbol:'none',data:dr.map(function(r){return +r.reorder.toFixed(1);}),lineStyle:{color:'#f59e0b'}},{name:'目标S',type:'line',symbol:'none',data:dr.map(function(){return q.targetStock;}),lineStyle:{type:'dotted',color:'#8b5cf6'}},{name:'当日入库',type:'bar',data:dr.map(function(r){return +r.incoming.toFixed(1);}),itemStyle:{color:'rgba(59,130,246,.45)'}}]}));if(ch)ch.on('click',function(e){if(typeof e.dataIndex==='number'){var r=dr[e.dataIndex];if(r.risk!=='正常')window.invV1OpenRisk(p.code,r.date);}});}
  if(STATE.tab===4&&STATE.scenarioRun){var sr=scenarioResult(),rr=project(p,{params:sr.newP,demandMult:sr.mult,leadExtra:sr.extra});initChart('invScenarioChart',mOpt({tooltip:{trigger:'axis'},legend:{data:['调整后期末库存','SS','目标S'],top:0,right:0},xAxis:{type:'category',data:rr.map(function(r){return shortDate(r.date);})},yAxis:{type:'value',name:'吨'},series:[{name:'调整后期末库存',type:'line',smooth:true,data:rr.map(function(r){return +r.closing.toFixed(1);}),itemStyle:{color:'#8b5cf6'},areaStyle:{color:'rgba(139,92,246,.08)'}},{name:'SS',type:'line',symbol:'none',data:rr.map(function(){return sr.newP.safetyStock;}),lineStyle:{type:'dashed',color:'#ef4444'}},{name:'目标S',type:'line',symbol:'none',data:rr.map(function(){return sr.newP.targetStock;}),lineStyle:{type:'dotted',color:'#06b6d4'}}]}));}
  if(STATE.tab===5){initChart('invHealthChart',{backgroundColor:'transparent',tooltip:{trigger:'item'},radar:{indicator:[{name:'满足率',max:100},{name:'低缺货',max:100},{name:'低超容',max:100},{name:'低库龄风险',max:100},{name:'策略有效',max:100}],axisName:{color:'#94a3b8'},splitLine:{lineStyle:{color:'#334155'}},splitArea:{areaStyle:{color:['rgba(15,21,37,.4)','rgba(17,24,39,.25)']}}},series:[{type:'radar',data:[{name:'综合健康度',value:[95.7,75,75,82,72],areaStyle:{color:'rgba(16,185,129,.18)'},lineStyle:{color:'#10b981'},itemStyle:{color:'#10b981'}}]}]});}
}

function openModal(id,title,body,width){closeModal(id);var host=document.createElement('div');host.id=id;host.innerHTML='<div class="modal-mask" onclick="if(event.target===this)closeModal(\''+id+'\')"><div class="modal-panel" style="width:'+(width||'720px')+'"><button class="modal-close" onclick="closeModal(\''+id+'\')">×</button><div class="page-title" style="font-size:18px">'+title+'</div><div class="mt-16">'+body+'</div></div></div>';document.body.appendChild(host);}
function addAudit(action,object,result){var now=new Date(),ts=now.toLocaleString('zh-CN',{hour12:false}).replace(/\//g,'-');STATE.audit.push({time:ts,user:'李明哲',action:action,object:object,result:result||'成功'});}

window.invV1Switch=function(i){STATE.tab=i;var c=document.querySelector('.content');if(c)c.scrollTop=0;render();};
window.invV1SelectProduct=function(code,tab){STATE.product=code;STATE.tab=Number(tab);render();};
window.invV1OpenNode=function(type,index){var f=FLOW[type],n=f.nodes[index];openModal('invNodeModal',f.code+'-'+n[0]+' · '+n[1],'<div class="inv-modal-grid"><div class="inv-modal-label">所属流程</div><div class="inv-modal-value">'+f.title+'</div><div class="inv-modal-label">执行角色</div><div class="inv-modal-value">'+n[2]+'</div><div class="inv-modal-label">输入</div><div class="inv-modal-value">'+n[3]+'</div><div class="inv-modal-label">输出</div><div class="inv-modal-value">'+n[4]+'</div><div class="inv-modal-label">处理说明</div><div class="inv-modal-value">'+n[5]+'</div><div class="inv-modal-label">异常/分支</div><div class="inv-modal-value">'+n[6]+'</div><div class="inv-modal-label">演示规则号</div><div class="inv-modal-value text-mono text-cyan">'+n[7]+'</div></div>');};
window.invV1OpenRisk=function(code,date){var p=getProduct(code),r=(STATE.projection[code]||[]).find(function(x){return x.date===date;});if(!r)return;var gap=r.closing<param(p).safetyStock?param(p).safetyStock-r.closing:Math.max(0,r.closing-capacityFor(p)),level=r.risk==='缺货'||r.risk==='容量冲突'?'红色':'黄色',action=r.locked?'记录预警并保持第1周锁定量；升级协调生产执行。':'形成补充调整差异，库存复核后提交生产计划员。';openModal('invRiskModal',r.risk+' · '+p.name+' · '+date,'<div class="inv-summary mb-16">'+summary('期末可用',fmt(r.closing,1)+'吨',r.closing<0?'danger':'warning')+summary('正式SS',fmt(param(p).safetyStock)+'吨')+summary('风险缺口/超量',fmt(gap,1)+'吨','danger')+summary('预警级别',level,'danger')+'</div><div class="inv-modal-grid"><div class="inv-modal-label">风险窗口</div><div class="inv-modal-value">'+(r.locked?'T+7锁定期':'第2至第4周滚动区')+'</div><div class="inv-modal-label">库存位置</div><div class="inv-modal-value">'+fmt(r.ip,1)+'吨</div><div class="inv-modal-label">按日再订货点 s</div><div class="inv-modal-value">'+fmt(r.reorder,1)+'吨（最早可用日前需求 + SS）</div><div class="inv-modal-label">建议处置</div><div class="inv-modal-value">'+action+'</div><div class="inv-modal-label">关联规则</div><div class="inv-modal-value text-mono text-cyan">INV-D-030 / INV-D-040 / '+(r.locked?'INV-D-050':'INV-D-070')+'</div></div><div class="inv-actions mt-16"><button class="btn btn-primary btn-sm" onclick="closeModal(\'invRiskModal\');invV1HandleDaily('+(r.locked?'true':'false')+')">执行建议处置</button><button class="btn btn-sm" onclick="closeModal(\'invRiskModal\')">关闭</button></div>');};
window.invV1Refresh=function(){var now=new Date();STATE.lastSnapshot=now.toLocaleString('zh-CN',{hour12:false}).replace(/\//g,'-');addAudit('刷新库存计算输入快照','STKSNP-DEMO','成功');render();};
window.invV1Export=function(){var blob=new Blob([JSON.stringify(D,null,2)],{type:'application/json;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='scos-inventory-demo-data.json';a.click();setTimeout(function(){URL.revokeObjectURL(a.href);},1000);addAudit('导出成品库存优化样例数据','inventory-demo-data.json','成功');};
window.invV1Entities=function(){var entities=D.entities.map(function(e){return '<div class="inv-entity"><div class="inv-entity-head"><span>'+e.name+'</span><span class="inv-source-id">'+e.code+'</span></div><div class="inv-field-chips">'+e.coreFields.map(function(f){return '<span class="inv-field-chip">'+f+'</span>';}).join('')+'</div></div>';}).join(''),ifs='<div class="overflow-auto mt-16"><table class="data-table"><thead><tr><th>接口</th><th>方向</th><th>内容</th><th>频率</th><th>状态</th></tr></thead><tbody>'+D.interfaces.map(function(i){return '<tr><td class="text-mono text-cyan">'+i.id+'</td><td>'+i.direction+'</td><td>'+i.content+'</td><td>'+i.frequency+'</td><td>'+statusTag(i.status)+'</td></tr>';}).join('')+'</tbody></table></div>';openModal('invEntityModal','七类逻辑数据实体与接口','<div class="inv-entity-grid">'+entities+'</div><div class="section-title mt-16"><span class="icon">●</span>接口可见性</div>'+ifs,'980px');};
window.invV1RecalcMonthly=function(){var p=getProduct(),ss=Math.max(0,Number(document.getElementById('invSS').value)||0),targetRaw=Math.max(ss+1,Number(document.getElementById('invTarget').value)||0),target=Math.min(capacityFor(p),targetRaw),lead=Math.max(1,Number(document.getElementById('invLead').value)||1),batch=Math.max(1,Number(document.getElementById('invBatch').value)||1);STATE.params[p.code]={safetyStock:ss,targetStock:target,leadDays:lead,batchSize:batch,batchEnabled:document.getElementById('invBatchOn').checked};STATE.monthlyStep=2;STATE.monthlyStatus=target<targetRaw?'参数草案 · S已按兼容容量收敛':'参数草案';addAudit('生成月度库存策略草案',p.code+' / DRAFT','成功');render();};
window.invV1AdvanceMonthly=function(){if(STATE.monthlyStep<6){STATE.monthlyStep++;STATE.monthlyStatus=['','','待评审','评审中','待确认','待审批','已发布 V1.1'][STATE.monthlyStep]||'处理中';if(STATE.monthlyStep===6){D.meta.strategyVersion='V1.1';D.meta.strategyId='STGY202610002';STATE.monthlyStatus='有效版本 V1.1';addAudit('发布月度库存策略','STGY202610002 / V1.1','成功');}}else{STATE.tab=2;STATE.weeklyStep=Math.max(STATE.weeklyStep,1);addAudit('进入周度计划分解','WRPL-DEMO','成功');}render();};
window.invV1ResetMonthly=function(){STATE.monthlyStep=2;STATE.monthlyStatus='参数草案';render();};
window.invV1AdvanceWeekly=function(){if(STATE.weeklyStep<8){STATE.weeklyStep++;STATE.weeklyStatus=['输入汇集','日度计算','周度汇总','评审中','库存确认','生产承接','排程确认','第1周待锁定','已发布'][STATE.weeklyStep]||'处理中';if(STATE.weeklyStep===8)addAudit('锁定并发布第1周补充计划','WRPL20260925001','成功');}render();};
window.invV1AcceptWeek=function(w,s){addAudit('更新生产承接状态','W'+w+' / '+s,'成功');STATE.weeklyStatus='生产承接更新';render();};
window.invV1HandleDaily=function(locked){if(locked){STATE.dailyAction='锁定期预警已记录 · 保持锁定量';addAudit('记录锁定期库存预警','T+7 / 保持锁定','成功');}else{STATE.dailyAction='非锁定期建议已提交生产端';addAudit('提交非锁定期补充调整建议','W2-W4 / 待生产确认','成功');}render();};
window.invV1RollLock=function(){addAudit('滚动锁定T+7','新增锁定1天','成功');STATE.dailyAction='已模拟次日滚动锁定 · 新增1天';render();};
window.invV1Event=function(k){STATE.scenario=k;STATE.scenarioRun=false;STATE.abnormalStep=0;render();};
window.invV1RunScenario=function(){var v=Math.max(0,Number(document.getElementById('invEventValue').value)||0);EVENTS[STATE.scenario].value=v;STATE.scenarioRun=true;STATE.abnormalStep=3;addAudit('生成异常调整策略草案',EVENTS[STATE.scenario].title+' / V1.1-DRAFT','成功');render();};
window.invV1AdvanceAbnormal=function(){if(!STATE.scenarioRun)return;if(STATE.abnormalStep<6){STATE.abnormalStep++;if(STATE.abnormalStep===6){STATE.abnormalPublished=true;D.meta.strategyVersion='V1.1-A';D.meta.strategyId='STGY202610002-A';addAudit('发布库存策略异常调整版本',D.meta.strategyId+' / '+D.meta.strategyVersion,'成功');}}render();};
window.invV1ResetScenario=function(){STATE.scenarioRun=false;STATE.abnormalStep=0;render();};
window.invV1AdvanceHealth=function(){if(STATE.healthPublished){openModal('invReportModal','库存健康度评价报告 · STKHLT-202609','<div class="inv-status-panel success"><b>报告已发布</b><br>评价期：2026-09 · 综合订单满足率 '+(D.health.reduce(function(a,h){return a+h.orderFillRate;},0)/D.health.length*100).toFixed(1)+'% · 麦芽糊精进入异常调整跟踪。</div>'+auditHTML());return;}if(STATE.healthStep<6){STATE.healthStep++;if(STATE.healthStep===6){STATE.healthPublished=true;addAudit('发布库存健康度报告','STKHLT-202609','成功');}}render();};

window.buildInventoryHTML=function(){return '<div></div>';};
window.initInventory=function(){render();};
try{PT.inventory='成品库存优化';PB.inventory='决策中心 / 成品库存优化';}catch(e){}
STATE.projection=projections();
})();
